# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  navieraapi:
    image: navieraapi
    build:
      context: .
      dockerfile: Naviera.API/Dockerfile
    ports:
      - 7078:7078
