# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  navieraapi:
    image: navieraapi
    build:
      context: .
      dockerfile: Naviera.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7078:7078
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
