version: '3.4'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    build:
      context: .
      dockerfile: ./Dockerfile
